### ISSUE TITLE
OSX App Checklist

### ISSUE THREAD

**Issue by gabriel** [keybase/client#227]
# Checklist for OSX Client
### Infrastructure:
- [x] msgpack RPC client
- [x] Handle cancelled "errors" properly
### Connect:
- [x] Signup
- [x] Login
- [x] Device provisioning
- [x] Save PGP key
- [x] PGP Keygen
- [x] PGP import manually (from bin or asc file)
- [ ] Handle errors like BAD_SIGNUP_EMAIL_TAKEN on login/signup
### User:
- [x] User profile
- [x] Track/Identify
- [x] Tracking popup
- [x] List (tracking)
- [x] List (trackers)
### App:
- [ ] More advanced OSX menu bar widget
- [ ] OS X Notifications
- [ ] Preferences Pane / Config
- [x] Debug Status (view log, show sock path and api endpoint)
- [ ] Option to use OSX Keychain to save password
- [ ] Better alert error UI (currently uses a NSAlert sheet
- [ ] Window restoration support
### Search:
- [x] Users (local), calls API directly though
- [x] Users (remote)
- [ ] Folders
- [ ] Global search bar?
### Devices:
- [x] List
- [x] Add
- [ ] Remove
### PGP:
- [x] Encrypt/decrypt/verify/sign (UI)
- [ ] View PGP Key info
### Installer/Updater:
- [x] DMG
- [x] keybased Installer (on first app run); includes launchd setup
- [x] Gatekeeper (waiting for itunesconnect to unfuck itself)
- [x] App updating
- [ ] Crash reporting #265 
- [x] Version numbers for .app and keybased in build
- [x] Option to automatically start at boot
