### ISSUE TITLE
CLI-feature parity

### ISSUE THREAD

**Issue by maxtaco** [keybase/client#246]
Here is a list of what the node cli gives us:
- [x] btc: add a signed cryptocurrency address to your profile
- [x] cert: print out the CA cert the client uses to authorize HTTPS connections
- [x] ~~dir: sign or verify a directory's contents~~
- [x] config: make an initial configuration file
- [x] decrypt: PGP decrypt a file (see #263)
- [x] encrypt: PGP encrypt a message and output to stdout or a file (see #260)
- [x] help: display help
- [x] id: Identify a user, but don't accept or reject trust
- [x] join: establish a new account on keybase.io
- [x] keygen: generate a new PGP public key and optionally push it to the server
- [x] list-signatures: list of your non-revoked signatures (bug in #247)
- [x] list-tracking: list people you are tracking (work in #70)
- [x] login: establish a session
- [x] logout: logout from the server
- [x] pull: pull your public (& private, if possible) key(s) from the server
- [x] push: push a PGP key from the client to the server (#228)
- [x] prove: add a proof of identity
- [x] reset: reset the local setup, deleting all local cached state (see #323)
- [x] revoke: revoke the currently active PGP keys (see #272, #183, #86)
- [x] revoke-signatures: revoke a proof or signature  (see #196)
- [x] search: search all users
- [x] sign: sign a message (bugs in ~~#248~~,  ~~#249~~, ~~#259~~, ~~#261~~)
- [x] status: print current status (related: #240)
- [x] ~~switch: switch to a different user, and nuke the current state~~
- [x] track: verify a user's authenticity and optionally track them
- [x] untrack: untrack this user (see #232)
- [ ] ~~update: update the keybase client software (see #382 for Linux)~~
- [x] verify: verify a file (see #263)
- [x] version: output version information about this client
