### ISSUE TITLE
Placeholder: node client compatibility with sibkey chains

### ISSUE THREAD

**Issue by maxtaco** [keybase/client#380]
Various components:
- [x] keybase/node-client#192 -- the bulk of the refactor
- [x] keybase/node-client#196 -- cleaning up how calling verify sigchains is called.
- [x] keybase/node-client#197 -- testing against new users
- [x] keybase/libkeybase-js#1 -- factor out new test cases into keybase-test-vectors, and eventually into the go code.
- [x] keybase/libkeybase-js#2 -- caching of signature verifications in the libkeybase-js library
- [x] keybase/node-client#198 -- integration of signature verification cache
