### ISSUE TITLE
test tracking statements (and the proofs) more rigorously

### ISSUE THREAD

**Issue by patrickxb** [keybase/client#480]
The current tracking tests only check for the existence of a tracking statement and don't verify anything about the tracking statement.  There are several things that would be good to test:
- [x] the status of the proofs (ok and broken)
- [x] a broken tracking statement where it contains a track failure (their proof changed since it was tracked)
- [x] a broken tracking statement when a proof is revoked
- [ ] ~~a track change (e.g. upgrade from http to https)~~ moved to #518 
- [x] an existing tracking statement is up to date
- [x] track a user with no proofs
- [x] track a user with some failed proofs
- [x] fixing a broken tracking statement works (existing statement has track failure or deleted proof)
- [x] upgrading a tracking statement when a new proof is added.

rooter can be used for proofs to make it easier to generate all these situations.
