### ISSUE TITLE
Milestone 1 Launch Plan

### ISSUE THREAD

**Issue by chrisnojima** [keybase/client#650]
This serves as a checklist of things we need to do before the M1 go client launch
- [x] Force all existing node users to update to the latest node client for compatibility (it's not forced, it's just voluntary for now)
- [ ] Test upgrade paths. Install the prod node client, do some stuff, install the go client, does it all still work? (keybase/client#801)
- [x] Make sure the basic commands (`signup`, `login`, `prove`...) don't print random warnings. (#802)
- [x] Make sure all the different `help` commands print the correct docs.
- [x] push to brew (do we solely control this?) (#486)
- [ ] Update website's installation instructions for mac users to say (keybase/keybase#433):
  - [ ] OSX: (someone needs to say what to put here)
  - [ ] Linux: (something here) 
- [ ] Update website's sample code to reflect Go changes and link to Go page (keybase/keybase#434)
- [ ] Update documentation:
  - [ ] Sigchain specifications (keybase/keybase#430)
  - [x] Keybase-style msgpacked signatures (keybase/keybase#429 and keybase/keybase#432)
  - [ ] New API endpoints in use (see keybase/keybase#435)

@keybase/owners Please fill in anything we need to do right before the launch
