### ISSUE TITLE
integrations: bitbucket (ToC Ticket)

### ISSUE THREAD

**Issue by maxtaco** [keybase/client#949]
The bitbucket integration has several components:
- [ ] keybase/keybase#461 --- server support
- [ ] keybase/client#948 --- Go client support
- [ ] keybase/proofs#19 --- proofs support
- [ ] keybase/node-client#211 --- node client support
